version: '3.8'

services:
  backend:
    build: .
    container_name: hendursaga
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs